config/routes.rb
Rails.application.routes.draw do
    get 'utilisateurs/index'

    resources :utilisateurs do
        resources :tweets
        member do
            get "liste_tweets"
            delete "utilisateur_delete"
            # post "add_follower"
        end

        resources :utilisateurs
        member do
            get "liste_add_follows"
            get "view_followers"
            post "/add/follower", to: 'utilisateurs#add_follower'
            delete "/remove/follower", to: 'utilisateurs#remove_follower'
        end

    end

    root to: 'utilisateurs#index'
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follow.rb
class Follow < ApplicationRecord
    belongs_to :follower, class_name: 'Utilisateur', :foreign_key => "follower_id"
    belongs_to :followed, class_name: 'Utilisateur', :foreign_key => "followed_id"
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :utilisateur
  validates :content, presence: true
end

app/models/utilisateur.rb
class Utilisateur < ApplicationRecord
    has_many :tweets, dependent: :delete_all
    has_many :follower, foreign_key: :follower_id, class_name: "Follow"
    has_many :follower, foreign_key: :followed_id, class_name: "Follow"

    has_many :followers, :through => :relations_to, :source => :follower
    has_many :followeds, :through => :relations_from, :source => :followed
    # belongs_to :utilisateur, required: false
    validates :prenom, presence: true
    validates :age, presence: true  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    def index
    end
    
    def new
    end
    
    def create
        @utilisateur = Utilisateur.find(params[:utilisateur_id])
        @tweet = @utilisateur.tweets.create(tweet_params)
        redirect_to utilisateur_path(@utilisateur)
    end
    
    def show
    end
    
    def edit
    end
      
    
    def update
    end
    
    def destroy
    end
      
    private 
    def tweet_params
        params.require(:tweet).permit(:content)
        
    end
end

app/controllers/utilisateurs_controller.rb
class UtilisateursController < ApplicationController
  def index
    @utilisateurs = Utilisateur.all
  end

  def new
    @utilisateur = Utilisateur.new
  end

  def create
    # render plain: params[:utilisateur].inspect
    @utilisateur = Utilisateur.new(utilisateur_params)
    if @utilisateur.save
      redirect_to @utilisateur
    else
      render 'new'
    end
  end

  def show
    @utilisateur = Utilisateur.find(params[:id])
  end

  def liste_tweets
    @utilisateur = Utilisateur.find(params[:id])
    @tweets = @utilisateur.tweets
 
    render partial: 'liste_tweets'
  end

  def liste_add_follows
    @followers = Utilisateur.find_by_sql("
      SELECT * From utilisateurs u
      WHERE u.id not in (
            SELECT id From utilisateurs u2
            INNER JOIN follows f ON f.follower_id = u2.id
            WHERE f.followed_id = #{ params[:id] })
      AND u.id <> #{ params[:id] }
    ")
    @utilisateur = Utilisateur.find(params[:id])
     
    render partial: 'liste_follows'
  end

  def view_followers
    @followers = Utilisateur.find_by_sql("
        SELECT * From utilisateurs u
        INNER JOIN follows f ON f.follower_id = u.id
        WHERE f.followed_id = #{ params[:id] }
      ")

    @utilisateur = Utilisateur.find(params[:id])
    render partial: 'view_followers'
  end
  

  def add_follower
    @follower = Utilisateur.find(params[:follower])
    @utilisateur = Utilisateur.find(params[:id])
    @follower = Follow.new({ "follower" => @follower, "followed"  => @utilisateur })
    @follower.save
    @followers = Utilisateur.find_by_sql("
      SELECT * From utilisateurs u
      WHERE u.id not in (
            SELECT id From utilisateurs u2
            INNER JOIN follows f ON f.follower_id = u2.id
            WHERE f.followed_id = #{ params[:id] })
      AND u.id <> #{ params[:id] }
    ")

    render partial: 'ajax_follows'
  end

  def remove_follower
    # Follow.where(followed_id: params[:id], follower_id: params[:follower]).destroy
    ActiveRecord::Base.connection.execute("
        DELETE FROM follows
        WHERE followed_id = #{ params[:id] }
        AND follower_id = #{ params[:follower] }
      ")

    @followers = Utilisateur.find_by_sql("
      SELECT * From utilisateurs u
      INNER JOIN follows f ON f.follower_id = u.id
      WHERE f.followed_id = #{ params[:id] }
    ")
    
    @utilisateur = Utilisateur.find(params[:id])

    render partial: 'ajax_view_followers'
  end
  
  

  def utilisateur_delete
    @utilisateur = Utilisateur.find(params[:id])
    @utilisateur.destroy

    @utilisateurs = Utilisateur.all
    
    render partial: 'liste_utilisateurs'
  end
  

  def edit
    @utilisateur = Utilisateur.find(params[:id])
  end
  

  def update
    @utilisateur = Utilisateur.find(params[:id])
    
    if @utilisateur.update(utilisateur_params)
      redirect_to @utilisateur
    else 
      render 'edit'
    end
  end

  def destroy
    @utilisateur = Utilisateur.find(params[:id])
    @utilisateur.destroy

    redirect_to utilisateurs_path
  end
  
  private 
  def utilisateur_params
    params.require(:utilisateur).permit(:nom, :prenom, :age)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/utilisateurs_helper.rb
module UtilisateursHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield :css%>
  </head>

  <body>
    <%= yield %>
    <%= yield :js%>
    <script src="https://kit.fontawesome.com/0ab26a83f7.js" crossorigin="anonymous"></script>
  </body>
</html>

app/views/tweets/_new.html.erb
<%= content_for :css do %>
<% end %>

<div = class="container">
    
    <%= form_with model: [@utilisateur, @utilisateur.tweets.build], html: {class: "mb-5 mt-5 p-5", :style => "border: solid #e1e2e2; margin-left: auto; margin-right: auto; width:50%;"}, local: true do |form| %>
        <div class="col d-flex justify-content-center mb-4">
            <h1>Nouveau twet<h2>
        </div>
        <div class="form-group ">
            <div class="col d-flex justify-content-center">
                <%= form.label :content, class: "" %>
            </div>

            <div class="col d-flex justify-content-center">
                <div class="col">
                    <%= form.text_field :content, class: "form-control" %>
                </div>
            </div>
        </div>

        <div class="form-row d-flex justify-content-center">
            <div class="col-4" style="padding-left: 34px;">
                <%= form.submit "envoyer", class: "btn btn-primary", style: "margin-right: 20px;" %>
            </div>
        </div>
    <% end %>
</div>

app/views/utilisateurs/_ajax_follows.html.erb
<div class="row m-5">
    <div class="col d-inline-flex  bd-highligh flex-wrap d-flex justify-content-center">
        <% @followers.each do |follow| %>
            <div class="card col-3 p-0 m-2">

        <%= image_tag "fake.png", alt: "Profil", :class => "card-img-top" %>
        <div class="card-body pt-2">
            <ul class="list-group list-group-flush mb-2">
                <li class="list-group-item">Nom : <%= follow.nom %></li>
                <li class="list-group-item">Prenom : <%= follow.prenom %></li>
                <li class="list-group-item">Age : <%= follow.age %></li>
            </ul>
            <div class="row">
                <div class="col d-flex justify-content-center">
                    <a href="<%= utilisateur_path(follow) %>" class="mr-2"><i class="far fa-id-card" style="font-size: 25px; color: black;"></i></a>
                    <i data-id="<%= @utilisateur.id %>" data-follower="<%= follow.id %>" class="ml-3 add-follower far fa-heart" style="font-size: 25px; color: black;"></i></a>
                </div>
            </div>
        </div>
    </div>            
        <% end %>
    </div>
</div>

app/views/utilisateurs/_ajax_tweets.html.erb
<div class="row m-5">
    <div class="col d-inline-flex  bd-highligh flex-wrap d-flex justify-content-center">
        <% @utilisateur.tweets.each do |tweet| %>
            
                <div class="card col-3 p-0 m-1">
                    <div class="card-header">
                        <div class="row">
                            <strong class="col d-flex justify-content-center pr-0">#Tweet</strong>
                        </div>
                    </div>
                    <div class="card-body">
                        <%= tweet.content %>
                    </div>
                </div>
            
        <% end %>
    </div>
</div>

<div class="row"> 
    <div class="col">
        <%= render 'tweets/new' %>
    </div>
</div>

app/views/utilisateurs/_ajax_view_followers.html.erb
<div class="row m-5">
    <div class="col d-inline-flex  bd-highligh flex-wrap d-flex justify-content-center">
        <% @followers.each do |follow| %>
            <div class="card col-3 p-0 m-2">

                <%= image_tag "fake.png", alt: "Profil", :class => "card-img-top" %>
                <div class="card-body pt-2">
                    <ul class="list-group list-group-flush mb-2">
                        <li class="list-group-item">Nom : <%= follow.nom %></li>
                        <li class="list-group-item">Prenom : <%= follow.prenom %></li>
                        <li class="list-group-item">Age : <%= follow.age %></li>
                    </ul>
                    <div class="row">
                        <div class="col d-flex justify-content-center">
                            <a href="<%= utilisateur_path(follow) %>" class="mr-2"><i class="far fa-id-card" style="font-size: 25px; color: black;"></i></a>
                            <i data-id="<%= @utilisateur.id %>" data-follower="<%= follow.id %>" class="ml-3 remove-follower fa fa-heart" style="font-size: 25px; color: black;"></i>
                        </div>
                    </div>
                </div>
            </div>            
        <% end %>
    </div>
</div>

app/views/utilisateurs/_form.html.erb
<div = class="container">
    <%= form_with model: @utilisateur, html: {class: "mt-5 p-5", :style => "border: solid #e1e2e2; margin-left: auto; margin-right: auto; width:50%;"}, local: true do |form| %>

        <div class="form-group ">
            <div class="col d-flex justify-content-center">
                <%= form.label :nom, class: "" %>
            </div>

            <div class="col d-flex justify-content-center">
                <div class="col">
                    <%= form.text_field :nom, class: "form-control" %>
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col d-flex justify-content-center">
                <%= form.label :prenom, class: "" %>
            </div>

            <div class="col d-flex justify-content-center">
                <div class="col">
                    <%= form.text_field :prenom, class: "form-control" %>
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col d-flex justify-content-center">
                <%= form.label :age, class: "" %>
            </div>

            <div class="col d-flex justify-content-center">
                <div class="col">
                    <%= form.number_field :age, class: "form-control" %>
                </div>
            </div>
        </div>

        <div class="form-row d-flex justify-content-center">
        <%# <div class="col-2"></div> %>
            <div class="col-4" style="padding-left: 34px;">
                <%= form.submit "envoyer", class: "btn btn-primary", style: "margin-right: 20px;" %>
            </div>

             <div class="col">
                <a href="<%= utilisateurs_path %>"><button class="btn btn-primary">retour</button></a>
            </div>

            <%# <div class="col">
                
            </div> %>
        </div>
    <% end %>
</div>

app/views/utilisateurs/_liste_follows.js.erb
$("#ajaxRendering").html("<%= j(render partial: "ajax_follows") %>")
AJAX_ADD.init()

app/views/utilisateurs/_liste_tweets.js.erb
$("#ajaxRendering").html("<%= j(render partial: "ajax_tweets") %>")

app/views/utilisateurs/_liste_utilisateurs.html.erb
<% @utilisateurs.each do |utilisateur| %>
    <div class="card col-3 p-0 m-2">
        <%= image_tag "fake.png", alt: "Profil", :class => "card-img-top" %>
        <div class="card-body pt-2">

            <div class="row d-flex justify-content-end">
                <div style="color:red" class="pr-0 col-3 supr-user show d-flex justify-content-end">
                    <i data-id="<%= utilisateur.id %>" style="font-size: 20px;" class="fas fa-times-circle user-delete"></i>
                </div>
            </div>
                     
            <ul class="list-group list-group-flush mb-2">
                <li class="list-group-item">Nom : <%= utilisateur.nom %></li>
                <li class="list-group-item">Prenom : <%= utilisateur.prenom %></li>
                <li class="list-group-item">Age : <%= utilisateur.age %></li>
            </ul>
            <div class="row">
                <div class="col d-flex justify-content-center">
                    <a href="<%= utilisateur_path(utilisateur) %>" class="mr-2"><i class="far fa-id-card" style="font-size: 25px; color: black;"></i></a>
                    <a href="<%= edit_utilisateur_path(utilisateur) %>"><i class="fas fa-edit" style="font-size: 25px; color: black"></i></a>
                </div>
                    
            </div>
        </div>
    </div>
<% end %>

app/views/utilisateurs/_view_followers.js.erb
$("#ajaxRendering").html("<%= j(render partial: "ajax_view_followers") %>")
AJAX_REMOVE.init()

app/views/utilisateurs/edit.html.erb
<div = class="container">
   <%= render 'form' %>
</div>

app/views/utilisateurs/index.html.erb
 <%= content_for :css do %>
   <%= stylesheet_link_tag "utilisateurs/utilisateurs-index" %>
 <% end %>
 <div class="container">
    <div class="row d-flex justify-content-center mb-4">
        <h1>Utilisateurs</h1>
    </div>

    

    <div class="container">

        <div class="col fixed-top mt-4 ml-2"><a href="<%= new_utilisateur_path %>" class=""><button class="btn btn-primary btn-rounded">ajouter</button></a></div>

        <div id="liste-users" class="col d-inline-flex  bd-highligh flex-wrap d-flex justify-content-center">
            <%= render 'utilisateurs/liste_utilisateurs' %>
        </div>
        
    </div>
</div>

<%= content_for :jq do %>
    <%= javascript_include_tag "utilisateurs/index.js" %>
<% end %>

app/views/utilisateurs/new.html.erb
<div = class="container">
   <%= render 'form' %>
</div>

app/views/utilisateurs/show.html.erb
<%= content_for :css do %>
    <%= stylesheet_link_tag "utilisateurs/utilisateurs-show" %>
<% end %>

<div class="container">
    <div class="col-2 mx-auto mt-md-5">
        <div class="row">
            <div class="col p-0">
                <%= image_tag "fake.png", alt: "Profil", :class => "card-img-top" %>
            </div>
        </div>

        <div class="row mt-md-4 p-0">
            <div class="col d-flex flex-row pl-0">
                <strong>Nom : </strong>
            </div>

            <div class="col d-flex flex-row-reverse p-0">
                <%= @utilisateur.nom %>
            </div>
        </div>

        <div class="row mt-md-1 p-0">
            <div class="col d-flex flex-row pl-0">
                <strong>Prénom : </strong>
            </div>

            <div class="col d-flex flex-row-reverse p-0">
                <%= @utilisateur.prenom %>
            </div>
        </div>

        <div class="row mt-md-1 p-0">
            <div class="col d-flex flex-row pl-0">
                <strong>Âge : </strong>
            </div>

            <div class="col d-flex flex-row-reverse p-0">
                <%= @utilisateur.age %>
            </div>
        </div>

        <div class="row mt-md-1 p-0">
            <div class="col d-flex flex-row p-0">
                <div class="col d-flex flex-row pl-0">
                    <a href="<%= utilisateurs_path %>"><button class="btn btn-primary"><i class="fas fa-home"></i></button></a>
                </div>
            </div>

            <%# <div class="col d-flex flex-row p-0">
                <div class="col d-flex flex-row p-0">
                    <button class="btn-menu-show"><%= link_to "Se faire des amis", liste_follows_utilisateur_path, remote: true %><%#</button>
                </div>
            </div> %>
        </div>
        
    </div>

    <div class="row mt-md-5 d-flex justify-content-center">
        <div class="p-0 mr-3">
            <button class="btn-menu-show"><%= link_to "Mes tweets", liste_tweets_utilisateur_path, remote: true %></button>
        </div>

        <div class="p-0 mr-3">
            <button class="btn-menu-show"><%= link_to "Se faire des amis", liste_add_follows_utilisateur_path, remote: true %></button>
        </div>

        <div class="p-0 mr-3">
            <button class="btn-menu-show"><%= link_to "Mes follows", view_followers_utilisateur_path, remote: true %></button>
        </div>
    </div>

    <div id="ajaxRendering">

        <%= render 'utilisateurs/ajax_tweets' %>

    </div>
    
</div>

app/views/utilisateurs/view_followers.html.erb
<div class="row m-5">
    <div class="col d-inline-flex  bd-highligh flex-wrap d-flex justify-content-center">
        <% @utilisateur.tweets.each do |tweet| %>
            
                <div class="card col-3 p-0 m-1">
                    <%= tweet.content %>
                </div>
            
        <% end %>
    </div>
</div>